// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fac
double fac(int n);
RcppExport SEXP _indetestc_fac(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(fac(n));
    return rcpp_result_gen;
END_RCPP
}
// temp
double temp(arma::mat a);
RcppExport SEXP _indetestc_temp(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(temp(a));
    return rcpp_result_gen;
END_RCPP
}
// fisher
double fisher(arma::mat a);
RcppExport SEXP _indetestc_fisher(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher(a));
    return rcpp_result_gen;
END_RCPP
}
// chisq_test
List chisq_test(arma::mat a);
RcppExport SEXP _indetestc_chisq_test(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(chisq_test(a));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_indetestc_fac", (DL_FUNC) &_indetestc_fac, 1},
    {"_indetestc_temp", (DL_FUNC) &_indetestc_temp, 1},
    {"_indetestc_fisher", (DL_FUNC) &_indetestc_fisher, 1},
    {"_indetestc_chisq_test", (DL_FUNC) &_indetestc_chisq_test, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_indetestc(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
