# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'@title Independence test of categorical variables
#'@description
#'@param a a matrix
#'@examples
#'chisq_test(matrix(c(98,38,289,67,41,262,13,8,57,18,12,30),4,3,b=T))
#'chisq_test(matrix(c(341,405,105,103,11,15),2,3,b=T))
#'@import Rcpp
#'@import RcppArmadillo
#'@export
fac <- function(n) {
    .Call(`_indetestc_fac`, n)
}

temp <- function(a) {
    .Call(`_indetestc_temp`, a)
}

fisher <- function(a) {
    .Call(`_indetestc_fisher`, a)
}

chisq_test <- function(a) {
    .Call(`_indetestc_chisq_test`, a)
}

